/*
core

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// BaseRuntime struct for BaseRuntime
type BaseRuntime struct {
	Name *string `json:"name,omitempty"`
}

// NewBaseRuntime instantiates a new BaseRuntime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseRuntime() *BaseRuntime {
	this := BaseRuntime{}
	return &this
}

// NewBaseRuntimeWithDefaults instantiates a new BaseRuntime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseRuntimeWithDefaults() *BaseRuntime {
	this := BaseRuntime{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BaseRuntime) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseRuntime) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BaseRuntime) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BaseRuntime) SetName(v string) {
	o.Name = &v
}

func (o BaseRuntime) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableBaseRuntime struct {
	value *BaseRuntime
	isSet bool
}

func (v NullableBaseRuntime) Get() *BaseRuntime {
	return v.value
}

func (v *NullableBaseRuntime) Set(val *BaseRuntime) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseRuntime) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseRuntime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseRuntime(val *BaseRuntime) *NullableBaseRuntime {
	return &NullableBaseRuntime{value: val, isSet: true}
}

func (v NullableBaseRuntime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseRuntime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


