version: '3.8'

services:
  core:
    build: core
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: "release"
      REDIS_ENDPOINT: "redis:6379"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-MINIO_SECRET_KEY}
      TMP_LAMBDA_TTL: ${TMP_LAMBDA_TTL:-900}
    depends_on:
      - minio
      - redis
  minio:
    image: "quay.io/minio/minio:RELEASE.2022-04-01T03-41-39Z"
    command: server --console-address ":9001" /data/minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-MINIO_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - "minio_data:/data"
  redis:
    image: "redis:6-alpine"
    volumes:
      - "redis_data:/data"

volumes:
  minio_data:
  redis_data:
